# Docker
# Build a Docker image
# https://docs.microsoft.com/en-us/azure/devops/pipelines/languages/acr-template?view=azure-devops

trigger:
- master

variables:
  tag: '$(Build.BuildId)'

stages:
- stage: Build
  displayName: Build and push stage
  jobs:
  - job: Build
    displayName: Build job
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - task: Docker@2
      displayName: Build and push an image to container registry x
      inputs:
        command: buildAndPush
        repository: api_test_hidde
        dockerfile: '**/Dockerfile'
        # registryName is the ContainerRegistry name according to the Azure DevOps Service connection!
        containerRegistry: $(registryName)
        tags: |
          $(tag)
