# Docker
# Build a Docker image
# https://docs.microsoft.com/en-us/azure/devops/pipelines/languages/acr-template?view=azure-devops

# Trigger on update of the folder app within the master branch
trigger:
  branches:
    include:
    - master
  paths:
    include:
    - app/

variables:
  pathHome: app
  tag: '$(Build.BuildId)'
  

stages:
- stage: Build
  displayName: Build and push stage
  jobs:
  - job: Build
    displayName: Build job
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - task: Docker@2
      displayName: Build and push an image to container registry x
      inputs:
        command: buildAndPush
        repository: api_test_hidde
        dockerfile: $(pathHome)/Dockerfile
        # registryName is the ContainerRegistry name according to the Azure DevOps Service connection!
        containerRegistry: $(registryName)
        tags: |
          $(tag)
