---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8s_ci_cd_tutorial
  labels:
    app: k8s_ci_cd_tutorial
    author: hidde
spec:
  replicas: 1 
  selector:
    matchLabels:
      app: k8s_ci_cd_tutorial
  template:
    metadata:
      labels:
        app: k8s_ci_cd_tutorial
        author: hidde
    spec:
      containers:
        - name: k8s_ci_cd_tutorial
          image: datahubcommonacr.azurecr.io/k8s_ci_cd_tutorial:##BUILD_ID##
          ports:
            - containerPort: 5002
          resources:
            requests:
              cpu: 250m
            limits:
              cpu: 500m
---
apiVersion: v1
kind: Service
metadata:
  name: k8s_ci_cd_tutorial
  labels:
    app: k8s_ci_cd_tutorial
    author: hidde
spec:
  selector:
    app: k8s_ci_cd_tutorial
  ports:
  - protocol: TCP
    port: 5002
    targetPort: 5002