# Artifact
# Build a K8s Deployment config artefact

# Trigger on update of the folder deployment_configs within the master branch
trigger:
  branches:
    include:
    - master
  paths:
    include:
    - deployment_configs/

pool:
  vmImage: 'Ubuntu 16.04'

steps:
- task: PublishBuildArtifacts@1
  displayName: 'publish deployment_configs folder as an artifact'
  inputs:
    pathToPublish: 'deployment_configs'
    artifactName: 'deploy_config_k8s_ci_cd_tutorial'
